### MUST FAIL REGISTRATION
POST http://localhost:3001/register
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### REGISTRATION
POST http://localhost:3001/register
Content-Type: application/json

{
  "name": "Brice Darnel",
  "email": "lewis18@doe.com",
  "password": "Password@@2026"
}



### LOGIN
POST http://localhost:3001/login
Content-Type: application/json

{

  "email": "lewis18@doe.com",
  "password": "Password@@2026"
}



### REGISTRATION
POST http://localhost:3001/refresh-token
Content-Type: application/json


{
 "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI2LCJpYXQiOjE3Mjg0MzEwNzIsImV4cCI6MTcyODQzNDY3MiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAxIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAxIn0.11a7h3R01VTil8W_W426oGOT-iYIY4gQ6_c6y7a1Usg"
}
