### MUST FAIL REGISTRATION
POST http://localhost:3001/register
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### REGISTRATION
POST http://localhost:3001/register
Content-Type: application/json

{
  "name": "Samira ines",
  "email": "ines@doe.com",
  "password": "Password@@2026"
}
